INSERT INTO Hermano (NUM_HER, NOMBRE, APELLIDOS, EMAIL, DNI, CUOTA, CARGO, DOMICILIO, PROVINCIA, VIVIENDA, MOVIL, FECHA_NAC, FECHA_ALTA) VALUES (NEXTVAL('hibernate_sequence'),'Fran', 'Ruiz', 'fran@email.com', '1111A', 50, 'Prioste', 'C/ Calle', 'Sevilla', 'Casa', '11111111', '2003-02-07',  '2003-05-14');
INSERT INTO Hermano (NUM_HER, NOMBRE, APELLIDOS, EMAIL, DNI, CUOTA, CARGO, DOMICILIO, PROVINCIA, VIVIENDA, MOVIL, FECHA_NAC, FECHA_ALTA) VALUES (NEXTVAL('hibernate_sequence'),'JJ', 'Ruiz', 'jj@email.com', '2222B', 50, 'Hermano', 'C/ Calle', 'Sevilla', 'Casa', '22222222', '1996-10-14',  '1996-12-10');

INSERT INTO Producto (ID, IMG, NOMBRE, DESCRIPCION, CANTIDAD, PVP) VALUES (NEXTVAL('hibernate_sequence'), 'https://customsacro.com/wp-content/uploads/2022/06/san-bernardo-2.jpg' ,'Pulsera San Bernardo', 'Pulsera de tela de la Hermadad de San Bernardo', 3, 1.00);
INSERT INTO Producto (ID, IMG, NOMBRE,DESCRIPCION, CANTIDAD, PVP) VALUES (NEXTVAL('hibernate_sequence'), 'https://sevilladejoya.es/117/medalla-san-bernardo.jpg' ,'Medalla de San Bernardo', 'Medalla Nuestra Señora del Refugio con reverso Santísimo Cristo de la Salud. Fabricada en Plata de Ley', 4, 45.97); 
INSERT INTO Producto (ID, IMG, NOMBRE,DESCRIPCION, CANTIDAD, PVP) VALUES (NEXTVAL('hibernate_sequence'), 'https://m.media-amazon.com/images/I/71otOqYdXjL._AC_UL400_.jpg' ,'Incensario de Cadenas', 'Incensario de orfebrería con diseño exclusivo y baño en plata', 7, 250.50);
INSERT INTO Producto (ID, IMG, NOMBRE,DESCRIPCION, CANTIDAD, PVP) VALUES (NEXTVAL('hibernate_sequence'), 'https://i.pinimg.com/originals/26/eb/b7/26ebb71bf7ce3244fd49148542ee0740.jpg' ,'Escudo de Capa', 'Escudo bordado a mano de la Hdad. San Bernardo', 10, 7.00);
INSERT INTO Producto (ID, IMG, NOMBRE,DESCRIPCION, CANTIDAD, PVP) VALUES (NEXTVAL('hibernate_sequence'), 'https://i.pinimg.com/736x/40/57/21/40572131fdfdec21ad896f6bf17ea9b2.jpg' ,'Escudo de Antifaz', 'Escudo bordado a mano de la Hdad. San Bernardo', 10, 6.00);
INSERT INTO Producto (ID, IMG, NOMBRE,DESCRIPCION, CANTIDAD, PVP) VALUES (NEXTVAL('hibernate_sequence'), 'https://sevilladejoya.es/369/pin-escudo-hermandad-san-bernardo.jpg' ,'Pin Escudo Hdad. San Bernardo', 'Pin Escudo de San Bernardo fabricado en Plata de Ley', 6, 29.99);
INSERT INTO Producto (ID, IMG, NOMBRE,DESCRIPCION, CANTIDAD, PVP) VALUES (NEXTVAL('hibernate_sequence'), 'https://herbolarioaguamar.com/wp-content/uploads/2020/12/carboncillos.jpg' ,'Carbón Litúrgico', 'Carbón Litúrgico de 40 mm. Cada paquete contiene 10 unidades', 4, 3.00);
INSERT INTO Producto (ID, IMG, NOMBRE,DESCRIPCION, CANTIDAD, PVP) VALUES (NEXTVAL('hibernate_sequence'), 'https://www.dcostal.com/2416-medium_default/incensario-nazareno-verde-y-blanco.jpg' ,'Incensario', 'Incensario Nazareno de cerámica', 8, 9.50);
INSERT INTO Producto (ID, IMG, NOMBRE,DESCRIPCION, CANTIDAD, PVP) VALUES (NEXTVAL('hibernate_sequence'), 'https://inciensoscofradeselcautivo.com/wp-content/uploads/2022/05/WhatsApp-Image-2022-12-13-at-20.53.21-430x573.jpeg' ,'Pack Incieso', 'Contiene:<br> 1 torre de cerámica <br> 1 barra de carbón <br> 1 bolsa del incienso más suave y dulce', 5, 11.40);